version: "3.3"

services:
  app:
    container_name: maw-los-fe
    image: maw-los-fe
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3005:80"
    restart: always
